defaults:
  - _self_
  - lightning_module: conf
experiment_config:
  _target_: src.config.ExperimentConfig
  model_config:
    _target_: src.config.ModelConfig
    model: resnet18
    pretrained: True
    embedding_size: 768
    metrics_include:
      - precision_at_1
      - NMI
    knn: 1
    optimizer_frequency: 5
    interval: epoch
    monitor: mean_valid_loss
  data_config:
    _target_: src.config.DataConfig
    dataset_name: metric_learning_dataset
    img_size:
    - 256
    - 256
    batch_size: 256
    data_split:
    - 0.8
    - 0.1
    - 0.1
    num_workers: 4
    pin_memory: true
    persistent_workers: true
  trainer_config:
    _target_: src.config.TrainerConfig
    min_epochs: 5
    max_epochs: 30
    check_val_every_n_epoch: 5
    log_every_n_steps: 1
    gradient_clip_val: null
    gradient_clip_algorithm: null
    deterministic: false
    fast_dev_run: false
    default_root_dir: null
    detect_anomaly: false
    accelerator: auto
  project_config:
    _target_: src.config.ProjectConfig
    project_name: metric_learning
    experiment_name: metric_learning
    track_in_clearml: true
